version: '2'
services:
  postgres:
    image: 'postgres:10'
    restart: always
    volumes:
      - './docker/postgres/data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=password456
      - TZ=America/Santiago
    ports:
      - '5432:5432'
